#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import * as z from "zod/v4";

const baseUrl = process.env.ABL_SERVER_URL || "http://127.0.0.1:3767";
const token = process.env.ABL_TOKEN;

if (!token) {
  console.error("ABL_TOKEN is required; use a token generated by the local daemon config");
  process.exit(1);
}

async function api(pathname, options = {}) {
  const response = await fetch(`${baseUrl}${pathname}`, {
    ...options,
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
      ...options.headers,
    },
  });
  const payload = await response.json();
  if (!response.ok || !payload.ok) {
    const error = payload.error || {};
    throw new Error(`${error.code || response.status}: ${error.message || "Request failed"}`);
  }
  return payload.result;
}

function textResult(result) {
  return {
    content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
  };
}

const server = new McpServer({
  name: "agent-browser-local",
  version: "0.2.0",
}, {
  instructions:
    "Contribution-only browser. Never use it to collect, enumerate, scrape, or export platform data. Take a fresh Snapshot before each action because refs expire. Use screenshot clicks only from the current screenshot. Login, verification, legal consent, creation, publishing, deletion, payment, and credit-consuming actions must be handed to the user; the daemon enforces these boundaries.",
});

server.registerTool(
  "browser_status",
  {
    description: "Read the current independent browser status and any human handoff request.",
    inputSchema: {},
  },
  async () => textResult(await api("/v1/status")),
);

server.registerTool(
  "browser_navigate",
  {
    description: "Navigate the independent browser to an http(s) URL.",
    inputSchema: { url: z.string().min(1) },
  },
  async ({ url }) =>
    textResult(
      await api("/v1/navigate", {
        method: "POST",
        body: JSON.stringify({ url }),
      }),
    ),
);

server.registerTool(
  "browser_snapshot",
  {
    description: "Read a bounded contribution-only accessibility snapshot. Refs expire after every action or navigation.",
    inputSchema: {},
  },
  async () =>
    textResult(await api("/v1/snapshot", { method: "POST", body: "{}" })),
);

server.registerTool(
  "browser_click",
  {
    description: "Click a control by a fresh Snapshot ref. Irreversible, auth and credit actions are blocked by the daemon.",
    inputSchema: { ref: z.string().min(1) },
  },
  async ({ ref }) =>
    textResult(
      await api("/v1/actions/click", {
        method: "POST",
        body: JSON.stringify({ ref }),
      }),
    ),
);

server.registerTool(
  "browser_fill",
  {
    description: "Fill a textbox by a fresh Snapshot ref. Passwords and verification inputs are blocked.",
    inputSchema: { ref: z.string().min(1), value: z.string().max(100_000) },
  },
  async ({ ref, value }) =>
    textResult(
      await api("/v1/actions/fill", {
        method: "POST",
        body: JSON.stringify({ ref, value }),
      }),
    ),
);

server.registerTool(
  "browser_upload",
  {
    description: "Bind one or more allowlisted local files to a native file input discovered by Snapshot.",
    inputSchema: {
      ref: z.string().min(1),
      files: z.array(z.string().min(1)).min(1).max(8),
    },
  },
  async ({ ref, files }) =>
    textResult(
      await api("/v1/actions/upload", {
        method: "POST",
        body: JSON.stringify({ ref, files }),
      }),
    ),
);

server.registerTool(
  "browser_screenshot",
  {
    description: "Capture the current viewport for a dynamic visual fallback. The screenshot id expires in 60 seconds or after page change.",
    inputSchema: {},
  },
  async () => {
    const result = await api("/v1/screenshot", { method: "POST", body: "{}" });
    const { dataBase64, mimeType, ...metadata } = result;
    return {
      content: [
        { type: "text", text: JSON.stringify(metadata, null, 2) },
        { type: "image", data: dataBase64, mimeType },
      ],
    };
  },
);

server.registerTool(
  "browser_click_visual",
  {
    description: "Click a point from the current screenshot only. Fixed or remembered coordinates are rejected as stale.",
    inputSchema: {
      screenshotId: z.string().uuid(),
      x: z.number().nonnegative(),
      y: z.number().nonnegative(),
    },
  },
  async ({ screenshotId, x, y }) =>
    textResult(
      await api("/v1/actions/visual-click", {
        method: "POST",
        body: JSON.stringify({ screenshotId, x, y }),
      }),
    ),
);

server.registerTool(
  "browser_handoff",
  {
    description: "Stop automation and ask the user to take over for login, verification or a final action.",
    inputSchema: { reason: z.string().min(1).max(500) },
  },
  async ({ reason }) =>
    textResult(
      await api("/v1/handoff", {
        method: "POST",
        body: JSON.stringify({ reason }),
      }),
    ),
);

await server.connect(new StdioServerTransport());
